version: '3.7'
services:
  golang:
    container_name: golang
    image: teamsnap/go-dev:latest
    command: ["tail", "-f", "/dev/null"]
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    volumes:
      - ..:/go/src/github.com/teamsnap/go-dev
    ports:
      - 6060:6060
