kind: pipeline
name: default

steps:
- name: frontend
  image: node
  commands:
  - npm --version

- name: backend
  image: golang
  commands:
  - env GOOS=linux GOARCH=amd64 go build -o go-dev.linux
  - env GOOS=darwin GOARCH=amd64 go build -o go-dev.darwin

- name: ping
  image: redis
  commands:
  - redis-cli -h cache ping

services:
- name: cache
  image: redis
