kind: pipeline
name: default

steps:
- name: ping
  image: redis
  commands:
  - redis-cli -h cache ping

- name: frontend
  image: node
  commands:
  - npm --version

- name: backend
  image: golang
  commands:
  - env GOOS=linux GOARCH=amd64 go build -o go-docker.linux
  - env GOOS=darwin GOARCH=amd64 go build -o go-docker.darwin

services:
- name: cache
  image: redis
